# set base image (host OS)
FROM teresahgao/superurop-grayscale-cnn:tensorflow-2.3.0

# set the working directory in the container
WORKDIR /

# copy the content of the local directory to the working directory
COPY ./main.py ./main.py
COPY ./Greyscale_Images_png/ ./Greyscale_Images_png/
